name: Release
concurrency:
  group: release-${{ github.repository }}

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'

env:
  FILE_PATH: "Containerfile"
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  lint-scan:
    name: Lint/scan image
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: .

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build/load image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: "${{ env.FILE_PATH }}"
          load: true
          push: false
          tags: app-image:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
        
      - name: Lint with Dockle
        uses: goodwithtech/dockle-action@main
        with:
          image: app-image:${{ github.sha }}
          format: 'list'
          exit-code: '0'
          exit-level: 'warn'

      - name: Scan with Trivy
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: app-image:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: "10m"

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - lint-scan
    if: ${{ startsWith(github.event.ref, 'refs/tags/v') }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: .

      - name: Log in to GitHub CR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: metadata
        name: Gather image metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Release image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: "${{ env.FILE_PATH }}"
          push: true
          labels: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
